name: "."
title: "Cristal Rivera "
description: |
  iyo-distill
output_dir: "docs"
navbar:
  logo:
    image: favicon.png
  search: true
  right:
    - text: "Posts"      
      href: index.html 
    - text: "About"
      href: about.html
     
output: distill::distill_article
